name: vault-check-v5

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get vault status
        id: status
        uses: w3-io/w3-vault-action@v0
        with:
          command: status
          environment: testing
          rpc-url: "https://base-mainnet.g.alchemy.com/v2/0L3k1EjL5mpti6pqRUi1y"
        bridge-allow:
          - "ethereum/*"
